// <auto-generated />
using System;
using GestaoProduto.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GestaoProduto.Infrastructure.Data.Migrations
{
    [DbContext(typeof(GestaoProdutoDbContext))]
    partial class GestaoProdutoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("GestaoProduto.Domain.Entities.Produtos.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CnpjFornecedor")
                        .HasColumnType("varchar(20)")
                        .HasColumnName("cnpj_fornecedor");

                    b.Property<DateTime>("DataFabricacao")
                        .HasColumnType("date")
                        .HasColumnName("data_fabricacao");

                    b.Property<DateTime>("DataValidade")
                        .HasColumnType("date")
                        .HasColumnName("data_validade");

                    b.Property<string>("DescricaoFornecedor")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("descricao_fornecedor");

                    b.Property<string>("DescricaoProduto")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("descricao_produto");

                    b.Property<int>("IdFornecedor")
                        .HasColumnType("int")
                        .HasColumnName("id_fornecedor");

                    b.Property<string>("SituacaoProduto")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('Ativo', 'Inativo')")
                        .HasDefaultValue("Ativo")
                        .HasColumnName("situacao_produto");

                    b.HasKey("Id");

                    b.ToTable("produto");
                });
#pragma warning restore 612, 618
        }
    }
}
